name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing workflow
        run: echo "Workflow works"
      - name: Testing pwd
        run: pwd
      - name: Testing whoami
        run: whoami
      - name: Testing ls
        run: ls
      - name: Testing ls slash
        run: ls /
