name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5
      - name: Testing pwd
        run: pwd
      - name: Testing whoami
        run: whoami
      - name: Testing ls
        run: ls
      - name: Testing ls slash
        run: ls /

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle
